#ifndef FIRMWARE_PUNCH_INFORMATION_SERVICE_H
#define FIRMWARE_PUNCH_INFORMATION_SERVICE_H

#define BT_UUID_PUNCH_INFORMATION_SERVICE_VAL \
	BT_UUID_128_ENCODE(0xe1e23000, 0xfee9, 0x4d67, 0xa4f5, 0xb5144cea14bd)

#define BT_UUID_PUNCH_SI_NUMBER_VAL \
	BT_UUID_128_ENCODE(0xe1e23001, 0xfee9, 0x4d67, 0xa4f5, 0xb5144cea14bd)


#define BT_UUID_PUNCH_INFORMATION_SERVICE          BT_UUID_DECLARE_128(BT_UUID_PUNCH_INFORMATION_SERVICE_VAL)
#define BT_UUID_PUNCH_SI_NUMBER                    BT_UUID_DECLARE_128(BT_UUID_PUNCH_SI_NUMBER_VAL)


#endif //FIRMWARE_PUNCH_INFORMATION_SERVICE_H
